In [2]:
# Question 1: Input from Keyboard a list of Fruit and do
# A. Remove the duplicate fruits
# B. Convert to Array
# C. Print the number of Fruits

# Question 2: Input from Keyboard a list of Colors and do 
# A. Make sure that all the input color in lowercase  
# B. Remove the duplicate Colors and remove the color "Black" in list
# C. Convert to Array and Print the number of Colors

# Question 3 : Write a program :
# A. Input a number of Order from Monday to Friday   
# B. Print the day of highest Order Number and lowest Order Number
# C. Print the sum and average Order Number in a week

# Question 4: Using Iris dataset to:
# A. Extract the text column species from the 1D iris
# B. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
# C. Find the mean, median, standard deviation of iris's sepallength
# D. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1
# E. Compute the softmax score of sepallength.
# F. Find the 5th and 95th percentile of iris's sepallength

In [3]:
import numpy as np

In [4]:
# Question 1
# fruit_list = input("Enter a list of fruits separated by spaces: ").split()

fruit_list = ["grape", "orange", "strawberry", "peach", "lemon", "lychee", "peach"]

In [5]:
# A. Remove the duplicate fruits
unique_fruits = np.unique(fruit_list)
unique_fruits

array(['grape', 'lemon', 'lychee', 'orange', 'peach', 'strawberry'],
      dtype='<U10')

In [6]:
# B. Convert to Array
fruit_array = np.array(unique_fruits)
fruit_array

array(['grape', 'lemon', 'lychee', 'orange', 'peach', 'strawberry'],
      dtype='<U10')

In [7]:
# C. Print the number of Fruits
len(fruit_array)

6

In [8]:
# Question 2
# color_list = input("Enter a list of colors separated by spaces: ").split()

color_list = ["orange", "purple", "BLUE", "black", "red", "green", "yeer"]

In [9]:
# A. Make sure that all the input color in lowercase  
color_list = [color.lower() for color in color_list]
color_list

['orange', 'purple', 'blue', 'black', 'red', 'green', 'yeer']

In [10]:
# B. Remove the duplicate Colors and remove the color "Black" in list
unique_colors = np.unique(color_list)
unique_colors = unique_colors[unique_colors != "black"]
unique_colors

array(['blue', 'green', 'orange', 'purple', 'red', 'yeer'], dtype='<U6')

In [11]:
# C. Convert to Array and Print the number of Colors
color_array = np.array(unique_colors)
color_array

array(['blue', 'green', 'orange', 'purple', 'red', 'yeer'], dtype='<U6')

In [12]:
len(color_array)

6

In [13]:
# Question 3
# A. Input a number of Order from Monday to Friday   
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
# orders = []
# for day in days:
#     order = int(input(f"Enter the number of orders for {day}: "))
#     orders.append(order)
orders = [180, 199, 176, 168, 170] 

In [14]:
# B. Print the day of highest Order Number and lowest Order Number
max_orders_day = days[orders.index(max(orders))]
max_orders_day

'Tuesday'

In [15]:
min_orders_day = days[orders.index(min(orders))]
min_orders_day

'Thursday'

In [16]:
# C. Print the sum and average Order Number in a week
total_orders = sum(orders)
total_orders

893

In [17]:
average_orders = total_orders / len(orders)
average_orders

178.6

In [18]:
# Question 4


# This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) 
# petal and sepal length, stored in a 150x4 numpy.ndarray
# The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length 
# and Petal Width.
# The below plot uses the first two features. See here for more information on this dataset.

# A. Extract the text column species from the 1D iris
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d

C:\Users\lyduc\AppData\Local\Temp\ipykernel_20272\567319283.py:12: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

In [19]:
species = np.array([r[4] for r in iris_1d])
species[:20]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'],
      dtype='|S15')

In [20]:
# B. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_2d = np.array([r.tolist()[:4] for r in iris_1d])
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [21]:
# C. Find the mean, median, standard deviation of iris's sepallength
sepal_length = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean_sepal_length = np.mean(sepal_length)
median_sepal_length = np.median(sepal_length)
std_sepal_length = np.std(sepal_length)
print(mean_sepal_length)
print(median_sepal_length)
print(std_sepal_length)

5.843333333333334
5.8
0.8253012917851409


In [22]:
# D. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1
standardized_sepal_length = (sepal_length - sepal_length.min()) / (
    sepal_length.max() - sepal_length.min()
)
standardized_sepal_length

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [23]:
# E. Compute the softmax score of sepallength.
softmax_score = np.exp(sepal_length) / np.sum(np.exp(sepal_length))
softmax_score

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [24]:
# F. Find the 5th and 95th percentile of iris's sepallength
np.percentile(sepal_length, q=[5, 95])

array([4.6  , 7.255])