<img src = 'https://codelearnstorage.s3.amazonaws.com/Upload/Blog/su-dung-thu-vien-scippy-trong-python-p1-63727958646.6719.jpg'></img>

<h1> Bài tập Scipy </h1>
<!-- <h2> Nhóm 5 </h2> -->
https://images.datacamp.com/image/upload/v1676303474/Marketing/Blog/SciPy_Cheat_Sheet.pdf



<h2> 1. Basic Matrix Routines </h2>
# 1.1. Inverse <br>
# 1.2. Norm<br>
# 1.3. Rank<br>
# 1.4. Determinant<br>
# 1.5. Solving linear problems<br>
# 1.6. Generalized inverse<br>

In [ ]:
# 1.1. Inverse
# Tìm ma trận nghịch đảo của ma trận  a
import numpy as np
from scipy import linalg

a = np.array([[1.0, 2.0], [3.0, 4.0]])
# inversed_a = ...
# np.dot(a, inversed_a)

In [ ]:
# 1.2. Norm<br>
# Tìm norm của ma trận a

# 5.477225575051661

5.477225575051661

In [ ]:
# 1.3. Rank<br>
# Tìm rank của ma trận a - numpy

# 2

2

In [ ]:
# 1.4 Determinant
# Tìm định thức của ma trận a

# -2.0

-2.0

In [ ]:
# 1.5. Solving linear problems
# Giải phương trình Ax = b (Tìm x)
A = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[1.0, 0.0], [3.0, 0.0]])


# array([[1.00000000e+00, 0.00000000e+00],
#        [8.32667268e-17, 0.00000000e+00]])

array([[1.00000000e+00, 0.00000000e+00],
       [8.32667268e-17, 0.00000000e+00]])

In [ ]:
# 1.5. Solving linear problems
# Giải phương trình Ax = b (Tìm x) bằng phương pháp least squared

(array([[ 1.00000000e+00,  0.00000000e+00],
        [-6.01857166e-16,  0.00000000e+00]]),
 array([], dtype=float64),
 2,
 array([5.4649857 , 0.36596619]))

In [ ]:
# 1.6. Generalized inverse
# Tính giả nghịch đảo (Moore-Penrose) của ma trận. - phương pháp least-squares

linalg.pinv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<h2>  2. Matrix Functions</h2>
# 2.1 Exponential Functions<br>
# 2.2 Logarithm Function<br>
# 2.3 Trigonometric Functions<br>
# 2.4 Hyperbolic Trigonometric Functions<br>
# 2.5 Matrix Sign Function<br>
# 2.6 Matrix Square Root<br>
# 2.7 Arbitrary Functions<br>

In [ ]:
# 2.1 Exponential Function
# Tính ma trận hàm mũ của hàm A: EA = e^A
A = np.array([[1.0, 2.0], [3.0, 4.0]])
linalg.expm(A)

array([[ 51.9689562 ,  74.73656457],
       [112.10484685, 164.07380305]])

In [ ]:
# 2.2 Logarithm Function
# Tính ma trận hàm log(A)
linalg.logm(A)

array([[-0.35043981+2.39111795j,  0.92935121-1.09376217j],
       [ 1.39402681-1.64064326j,  1.04358699+0.7504747j ]])

In [ ]:
# 2.3 Trigonometric Functions

# Tính ma trận sin(A)

# Tính ma trận cos(A)

# Tính ma trận tan(A)

array([[-0.60507478, -0.31274165],
       [-0.46911248, -1.07418726]])

In [ ]:
# 2.4 Hyperbolic Trigonometric Functions
# Tính ma trận hyperbol sin(A)

# Tính ma trận hyperbol cos(A)

# Tính ma trận hyperbol tan(A)

In [ ]:
# 2.6 Matrix Square Root
# Tìm x trong phương trình X^2 = A
A = np.array([[1.0, 3.0], [1.0, 4.0]])
# linalg.sqrtm(A)

array([[0.75592895, 1.13389342],
       [0.37796447, 1.88982237]])

In [ ]:
# 2.7 Arbitrary Functions
# Tạo ma trận B = A^2 + 4 *A + 2
A = np.array([[1.0, 3.0], [1.0, 4.0]])
# linalg.funm(a, lambda x: x*x + 4*x + 2)

array([[12., 17., 20.],
       [ 8., 17., 10.],
       [ 7.,  9., 11.]])

<h2> 3. Decompositions </h2>
# 3.1 Eigenvalues and Eigenvectors <br>
# 3.2 Singular Value Decomposition<br>
# 3.3 LU Decomposition<br>

In [ ]:
# 3.1 Eigenvalues and Eigenvectors
# Tìm các trị riêng và vector riêng của A
A = np.array([[1.0, 3.0], [1.0, 4.0]])
# la, v = linalg.eig(A)

# print(la)
# print(v)

[0.20871215+0.j 4.79128785+0.j]
[[-0.96693047 -0.62052031]
 [ 0.25504011 -0.78419037]]


In [ ]:
# 3.2 Singular Value Decomposition
# Phân tích suy biến ma trận A
A = np.array([[1.0, 3.0], [1.0, 4.0]])
# U,s,Vh = linalg.svd(A)
# print(U)
# print(s)
# print(Vh)
# M,N = A.shape

# Sig = linalg.diagsvd(s,M,N)
# Sig

[[-0.60828716 -0.79371704]
 [-0.79371704  0.60828716]]
[5.1925824 0.1925824]
[[-0.27000134 -0.96285995]
 [-0.96285995  0.27000134]]


array([[5.1925824, 0.       ],
       [0.       , 0.1925824]])

In [ ]:
# 3.3 LU Decomposition
# Phân tích LU ma trận A
P, L, U = linalg.lu(A)
print(P, L, U)

[[1. 0.]
 [0. 1.]] [[1. 0.]
 [1. 1.]] [[1. 3.]
 [0. 1.]]


<br>
<img src = 'https://images.datacamp.com/image/upload/f_auto,q_auto:best/v1625838166/SciPy_Cheat_Sheet-_Linear_Algebra_in_Python_ff0oa8.png'></img>

<h2> 4. Optimize </h2>

**Bài 1**
> Một công ty dầu có 2 nhà máy lọc dầu.

>> Nhà máy 1 mất 20,000 đô/ngày để chạy. Mỗi ngày nhà máy sẽ sản xuất được 400 thùng dầu cao cấp, 300 thùng dầu trung cấp, 200 thùng dầu cấp thấp.

>> Nhà máy 2 hiện đại hơn, mất 25,000 đô/ngày để chạy. Mỗi ngày nhà máy sản xuất được 300 thùng dầu cao cấp, 400 thùng dầu trung cấp, 500 thùng dầu cấp thấp mỗi ngày.
Công ty nhận được đơn hàng yêu cầu 25,000 thùng dầu cao cấp, 27,000 thùng dầu trung cấp, 30,000 thùng dầu cấp thấp.

> Hỏi bao nhiêu ngày mỗi nhà máy lọc dầu cần chạy để giảm chi phí chạy đến mức tối thiểu mà vẫn có thể lọc dầu được đáp ứng được theo đơn hàng?

In [10]:
# We define x0 is the number of working days for the first factory
#           x1 is the number of working days for the second factory

# Function to optimize: Minimize the operation cost
# 20_000 * x0 + 25_000 * x1

# Constraint functions
# 400 * x0 + 300 * x1 >= 25_000
# 300 * x0 + 400 * x1 >= 27_000
# 200 * x0 + 500 * x1 >= 30_000

from scipy.optimize import linprog

c = [20_000, 25_000]
A_ub = [[-400, -300], [-300, -400], [-200, -500]]
b_ub = [-25_000, -27_000, -30_000]
x0_bounds = (0, None)
x1_bounds = (0, None)

result = linprog(c=c, A_ub=A_ub, b_ub=b_ub, bounds=[x0_bounds, x1_bounds])
print(result.fun)
print(result.x)
print(result.message)

1750000.0
[25. 50.]
Optimization terminated successfully. (HiGHS Status 7: Optimal)


**Bài 2**
> Tìm nghiệm của phương trinh
>> f(x) = x^3 − 100x^2 − x + 100

> Sử dụng hàm f_solve.

In [38]:
from scipy.optimize import root
import numpy as np


# Define your equation as a Python function
def equation(x):
    return x**3 - 100 * x**2 - x + 100


# Generate an initial guess array spanning the range where roots are expected


# Find all roots of the equation without specifying initial guesses
all_roots = []
for x0 in range(-200, 200, 1):
    sol = root(equation, x0=x0)
    if round(sol.x[0], 5) not in all_roots:
        all_roots.append(round(sol.x[0], 5))

print(all_roots)

[-1.0, 100.0, 1.0]


**Bài 3**
> Tính tích phân của một hàm số. Tính tích phân của f(x) = x^2 từ 0 đến 1

> Sử dụng câu lệnh integrate.quad

In [12]:
from scipy import integrate
import numpy as np

x2 = lambda x: x**2
integrate.quad(x2, 0, 1)

(0.33333333333333337, 3.700743415417189e-15)