# Keras Tutorials

### Run with GPU (if GPU faster CPU)

In [40]:
# Check for GPU availability
import tensorflow as tf
print(len(tf.config.experimental.list_physical_devices('GPU')) > 0)

True


In [41]:
tf.config.set_visible_devices([], 'GPU')
# physical_devices = tf.config.experimental.list_physical_devices('GPU')
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

## Generate data

In [42]:
import numpy as np
import random
from random import randint
from sklearn.utils import shuffle
from  sklearn.preprocessing import MinMaxScaler

In [43]:
train_labels = []
train_samples = []

### Example data:
- An experimental drug was tested on individuals from ages 13 to 100 in a clinical trial.
- The trial had 2100 participants. Half were under 65 years old, half were 65 years or older.
- Around 95% of patients 65 or older experienced side effects.
- Around 95% of patients under 65 experienced no side effects.

In [44]:
random.seed(0)

for i in range(50):
    # The ~5% of younger individuals who did experience side effects
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)

    # The ~5% of older individuals who did not experience side effects
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):
    # The ~95% of younger individuals who did not experience side effects
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(0)

    # The ~95% of older individuals who experience side effects
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(1)

In [45]:
train_samples = np.array(train_samples)
train_labels = np.array(train_labels)

In [46]:
train_samples

array([37, 91, 15, ..., 91, 17, 99])

In [47]:
train_labels

array([1, 0, 1, ..., 1, 0, 1])

In [48]:
train_samples, train_labels = shuffle(train_samples, train_labels)

In [49]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1, 1))

In [50]:
scaled_train_samples

array([[0.83908046],
       [0.66666667],
       [0.36781609],
       ...,
       [0.37931034],
       [0.94252874],
       [0.08045977]])

## Simple tf.keras Sequential Model

In [51]:
# For building models
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Activation, Dense

# For training models
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

## Build the Model

In [52]:
model = Sequential([
    Dense(name="Layer_2", units=16, input_shape=(1,), activation="relu"), # The first hidden layer (the second layover overall)
    Dense(name="Layer_3", units=32, activation="relu"),
    Dense(name="Layer_4", units=2, activation="softmax")
])

In [53]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Layer_2 (Dense)             (None, 16)                32        
                                                                 
 Layer_3 (Dense)             (None, 32)                544       
                                                                 
 Layer_4 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [54]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [55]:
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30


189/189 - 0s - loss: 0.6839 - accuracy: 0.5392 - val_loss: 0.6743 - val_accuracy: 0.6143 - 428ms/epoch - 2ms/step
Epoch 2/30
189/189 - 0s - loss: 0.6617 - accuracy: 0.6455 - val_loss: 0.6519 - val_accuracy: 0.6667 - 155ms/epoch - 818us/step
Epoch 3/30
189/189 - 0s - loss: 0.6400 - accuracy: 0.6921 - val_loss: 0.6301 - val_accuracy: 0.6952 - 146ms/epoch - 772us/step
Epoch 4/30
189/189 - 0s - loss: 0.6147 - accuracy: 0.7413 - val_loss: 0.6043 - val_accuracy: 0.7333 - 146ms/epoch - 772us/step
Epoch 5/30
189/189 - 0s - loss: 0.5891 - accuracy: 0.7704 - val_loss: 0.5796 - val_accuracy: 0.7524 - 145ms/epoch - 766us/step
Epoch 6/30
189/189 - 0s - loss: 0.5630 - accuracy: 0.7894 - val_loss: 0.5538 - val_accuracy: 0.7810 - 157ms/epoch - 833us/step
Epoch 7/30
189/189 - 0s - loss: 0.5358 - accuracy: 0.8042 - val_loss: 0.5273 - val_accuracy: 0.7905 - 151ms/epoch - 800us/step
Epoch 8/30
189/189 - 0s - loss: 0.5085 - accuracy: 0.8228 - val_loss: 0.5012 - val_accuracy: 0.8048 - 152ms/epoch - 805us/st